- name: Nginx install and start services
  hosts: frontend
  tasks:
  - name: install nginx
    ansible.built.package:
      name: nginx
      state: present
  - name: Stat nginx services
    service:
      name: nginx
      state: started
      enabled: yes