- name: ansible varabiles
  hosts: frontend
  vars:
    course: "Ansible"
    traine: "Shiva"
    duration: "150h"
  tasks:
    - debug:
        msg: "I am learning {{ course }} from {{ traine }} and duration is {{ duration }}"
        